module.exports = Object.freeze({
    nbuCurr: [
        "nbu-USD",
        "nbu-EUR",
        "nbu-PLN",
        "nbu-CZK",
        "nbu-DKK",
        "nbu-NOK",
        "nbu-CAD",
        "nbu-GBP",
        "nbu-CNY",
        "metal-XAU",
        "metal-XAG",
        "metal-XPT",
        "metal-XPD",
    ],
    monoList: ["mono-USD", "mono-EUR", "mono-PLN", "mono-GBP"],
    privat: ["privat-online", "privat-offline"],
    privatCurr: ["offline-USD", "offline-EUR", "online-USD", "online-EUR"],
    cryptoList: [
        "price-BTC",
        "price-ETH",
        "price-BCH",
        "price-LTC",
        "price-SOL",
        "price-XRP",
        "price-DOT",
        "price-DOGE",
        "price-BNB",
    ],
});